name: publish

on:
  push:
    branches: [ main ]
    paths:
      - "package.json"
      - "package-lock.json"

permissions:
  contents: write
  id-token: write
  packages: read

concurrency:
  group: publish-frp-cli
  cancel-in-progress: false

env:
  NODE_VERSION: "20"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - id: pkg
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - id: check
        env:
          NAME: ${{ steps.pkg.outputs.name }}
          VERSION: ${{ steps.pkg.outputs.version }}
        run: |
          if npm view "$NAME@${VERSION}" version --silent > /dev/null 2>&1; then
            echo "should_publish=false" >> $GITHUB_OUTPUT
          else
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - if: steps.check.outputs.should_publish == 'true'
        run: npm ci

      - if: steps.check.outputs.should_publish == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public

      - if: steps.check.outputs.should_publish == 'true'
        run: |
          git tag "v${{ steps.pkg.outputs.version }}"
          git push origin "v${{ steps.pkg.outputs.version }}"
